### ISSUE TITLE
전투 강화 장비 번역 기준

### ISSUE THREAD

**Issue by jth1324** [2hh8899/FTL-CE-Translation#11]
전투 강화 장비 번역할때,

(텔레포터 교란 장치) 이렇게, 교란 띄우고 장치를 할 껀지.

아니면 그냥 붙여서 (텔레포터 교란장치)로 번역 할 껀지. 붙이는 게 좀 더 보기 편한데, 아예 전부 붙이는 게 어떰?

약간 통일성이 어긋나는데.

**Comment by 2hh8899** [comment]
그렇다면 붙이는 쪽으로 가도록 합시다
