### ISSUE TITLE
안녕하세요. FTL CE 번역 참여 하겠습니다.

### ISSUE THREAD

**Issue by flameblast12** [2hh8899/FTL-CE-Translation#19]
events_fuel.xml.append 부터 번역하겠습니다.
그리고 무장이나 전투장비 번역된건 어디서 볼 수 있나요?

**Comment by jth1324** [comment]
blueprints.xml.append. dlcBlueprints.xml.append. 이게 전투 장비 관련된 번역임. 상점 관련된 번역 중 [내용] 관련된 문장은 아무 섹터 파일 뜯어서 참조하는 게 좋음.

blueprints.xml.append.에 교역물품도 적혀져 있으니 참조.

팀_왈도의_바닐라FTL_한패.xml 에 있는 내용일 경우 그대로 복붙하는 걸 추천
