### ISSUE TITLE
산발형 버레처럼 무기 중에 장비 피해가 이상한 부분 수정해야함

### ISSUE THREAD

**Issue by jth1324** [2hh8899/FTL-CE-Translation#24]
![오류](https://user-images.githubusercontent.com/55336603/67926450-661b3b80-fbf9-11e9-8861-3aad9ad1f996.png)

일반 피해 1
장비 피해 -1은

게임상으로 

일반 피해 1
장비 피해 0 (1-1)

형식이라. 수리 폭탄 계열을 제외한 나머지 무기에서 장비 피해를 다시 넣어야 함. 지금은 써보면 이해하는데, 안써보면 무슨 말인지 이해하기 힘듬.

**Comment by 2hh8899** [comment]
저 부분은 무기 성능에서 그대로 데이터를 뽑아와서 출력되는 곳이라, 수정하려면 장비 피해 그 자체를 올리지 않으면 불가능합니다.
misc.xml.rawappend에 저 부분 번역 관련은
`<text name="system_damage">장비 피해:</text>`
라고만 표기되어 있습니다.
