### ISSUE TITLE
무기명 번역은 좋은데 한가지만 더 번역하자

### ISSUE THREAD

**Issue by jth1324** [2hh8899/FTL-CE-Translation#3]
시작할때, 함선보면 무기 번역은 다 되어 있는데 함선 창에 달린 무기 축약형은 영어로 되어 있다. 아마 무기 파트 근처에 축약형도 번역하는 부분 있을 텐데 하는 김에 그거도 한글로 번역하자.

**Comment by 2hh8899** [comment]
좋은 생각인거같군요. 일단 인게임에서 축약형을 번역했을때 어떻게 보일지 확인한 후에 결정해보죠

**Comment by 2hh8899** [comment]
FTL갤에 사진 올리긴 했는데, 축약형 번역하면 상태가 영 안좋아보입니다. 확인부탁

**Comment by jth1324** [comment]
확인함. 경량형 레이저 같은 무기는 그냥 넣고, 안티 바이오 폭탄 같은 글자가 짤릴만한 무기는 좀 더 축약하는 게 좋은 거 같음. 어차피 원본 CE 모드에서도 무기 이름이 짤리는 부분이 꽤 있으니 우리가 해결할 수 있는 부분은 아님. 안티 바이오 폭탄은 안티 바이오 B. 안티 바이오 빔은 안티 바이오 BM. 이런 식으로 짤리는 이름들은 좀 더 축약시키는 게 더 좋을듯,

**Comment by jth1324** [comment]
그리고 오래된 레이저는 구식 레이저로 바꾸는 게 어떰? 무기에서 오래됬다는 말은 구형이나 구식을 의미하는 거 같은데.
