### ISSUE TITLE
events_ships.xml.append 번역 시작

### ISSUE THREAD

**Issue by flameblast12** [2hh8899/FTL-CE-Translation#34]

**Comment by flameblast12** [comment]
합치기 충돌 문제를 방지하려면 어떻게 해야 하는가요?

**Comment by 2hh8899** [comment]
자신이 수정하던 파일이 합치기 이전에 다른 사람에 의해 수정될 경우 충돌이 발생합니다. 방지하려면 그냥 브랜치 땄던거 최신으로 바꿔주기만 하면 됩니다 💕
