### ISSUE TITLE
섹터 번역 안된 것 있음

### ISSUE THREAD

**Issue by jth1324** [2hh8899/FTL-CE-Translation#38]
![섹터](https://user-images.githubusercontent.com/55336603/69473404-80f75f00-0df7-11ea-80f5-c6badbc1f10f.png)

몇몇 구역 번역이 안됨

**Comment by 2hh8899** [comment]
확인 결과 이미 번역된 부분이며, 전체 파일 검색을 돌려보았을 때도 일치하는 문장이 나오지 않습니다. 다시 번역패치한 후에도 반복되면 다시 제보 부탁드립니다. 💕
