### ISSUE TITLE
섹터 번역 일부분 적용안됨

### ISSUE THREAD

**Issue by jth1324** [2hh8899/FTL-CE-Translation#39]
![섹터2](https://user-images.githubusercontent.com/55336603/69496010-b93e9080-0f10-11ea-8602-ef57e1c438ac.png)

번역은 되어있지만 번역이 적용안되는 섹터가 존재.

재패치 이후에도 동일한 문제

**Comment by 2hh8899** [comment]
모든 파일을 자세히 확인해봐도 저 미번역 문장의 출력원인을 찾을 수 없었습니다. 다른 원인이 혹시 있는지 찾아보겠습니다.

**Comment by jth1324** [comment]
원인을 찾은듯. CE 뮤직 에드온 모드를 써서 이름 데이터가 덮어써진듯. 따로 찾을 필요 없는듯함.
