### ISSUE TITLE
이 부분 번역이 안됨

### ISSUE THREAD

**Issue by jth1324** [2hh8899/FTL-CE-Translation#41]
![번역 3](https://user-images.githubusercontent.com/55336603/69497259-40463580-0f1e-11ea-8a5a-8d93f6b01269.png)

**Comment by 2hh8899** [comment]
확인결과 CE리소스팩 쪽에서 추가하는 배경 이미지에 그대로 영어글을 박아넣어 만들어진 녀석입니다. 이것의 한글패치는 따로 진행하겠습니다.
