### ISSUE TITLE
events.xml.append 번역 시작

### ISSUE THREAD

**Issue by jth1324** [2hh8899/FTL-CE-Translation#43]
events.xml.append 번역 시작

**Comment by jth1324** [comment]
다른 거 먼저 함.

**Comment by jth1324** [comment]
10000 줄 번역하고 합치기하려고 했는데, 합치기가 안됨

**Comment by jth1324** [comment]
번역양이 많아서 스크립트 만줄 번역할때마다 합치기 하려고 하는데, 파일 용량이 커서 합치기가 안됨.

**Comment by 2hh8899** [comment]
"수정" 으로 번역 적용이 불가능할때는 그냥 "파일 업로드"를 사용하시면 같은 이름의 파일은 겹쳐집니다. 이를 활용하시면 됩니다.


진짜 엄청 열일해주셔서 감사합니다 SENSEI 💕😭
